/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.15
 * Generated at: 2017-09-29 07:44:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.myList;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class showDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<script src='/jquery/jquery-3.2.1.js'></script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("\t<div id='menuDiv' style='width: 100%; height: 10vh; border-color: black; border-style: solid; border-width: 1px;'>\t\t\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/menubar/menubar.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t<div id='chat' style='width: 20%; height: 80vh; border-color: black; border-style: solid; border-width: 1px; float: left;' align=\"center\">\t\t\t\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/chat/chat.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div id='content' style='width: 60%; border-color: black; border-style: solid; border-width: 1px; float: left; min-height: 80vh;overflow: auto;'>\t\t\r\n");
      out.write("\t\t<div style='height:40vh; width: 90%; margin-top: 5vh; margin-left: 5%;'>\r\n");
      out.write("\t\t\t<!-- 제목 div 시작 -->\r\n");
      out.write("\t\t\t<div style='height:5vh; width: 90.2%; border: 1px solid black;'>\r\n");
      out.write("\t\t\t\t<div style=\"float: left;width: 70%;\"><a>제목:\tpostTitle</a></div>\r\n");
      out.write("\t\t\t\t<div style=\"float: left;width: 29%;\" align=\"right\"><a>작성자: userId\t등록일: regDate</a></div>\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 제목 div end-->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- photo div start-->\r\n");
      out.write("\t\t\t<div style='height:40vh; width: 60%; border: 1px solid black; float: left'>\r\n");
      out.write("\t\t\t\t<img src = '/img/sell_example/sell");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.postNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".jpg' style=\"width: 100%; height: 40vh;\">\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- photo div end-->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- informatoin div start-->\r\n");
      out.write("\t\t\t<form id='auctionOrBuyNow' method='post'>\r\n");
      out.write("\t\t\t\t<input name='postNum' type=\"hidden\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.postNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>\r\n");
      out.write("\t\t\t\t<div style='height:40vh; width: 30%; border: 1px solid black; float: left'>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" readonly value='상품 카테고리' style='width:99%; height: 5vh; '><br>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" readonly value='상세 상품명' style='width:99%; height: 5vh;'><br>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" readonly value='상품 등급' style='width:50%; height: 5vh;'><a>등급 기준 보기</a><br>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" readonly value='현재가' style='width:99%; height: 5vh;'><br>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" readonly value='즉시 구매가' style='width:99%; height: 5vh;'><br>\r\n");
      out.write("\t\t\t\t\t<input id = 'increasePrice' type=\"text\" placeholder=\"입찰가를 입력해주세요\" style='width:99%; height: 5vh;'><br>\r\n");
      out.write("\t\t\t\t\t<button id= 'auctonBtn' type=\"button\" style='width:45%; height: 2.5vh;margin-left: 3%;margin-top: 0.5vh'>입찰하기</button>\r\n");
      out.write("\t\t\t\t\t<button id= 'buyNowBtn' type=\"button\" style='width:45%; height: 2.5vh; margin-top: 0.5vh'>즉시구매</button><br>\r\n");
      out.write("\t\t\t\t\t<button id= 'actuonCancelBtn' type=\"button\" style='width:45%; height: 2.5vh; margin-left: 3%'>입찰취소</button>\r\n");
      out.write("\t\t\t\t\t<button id= 'myListBtn' type=\"button\" style='width:45%; height: 2.5vh;'>관심상품 등록</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<!-- informatoin div ends-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- post Content div start-->\r\n");
      out.write("\t\t<div style='width: 81.5%; margin-top: 5vh; margin-left: 5%;'>\t\t\r\n");
      out.write("\t\t\t\t<p>게시물 내용: SELECT POST_CONTENT FROM S_POST WHERE POST_NUM = postNum<br>\r\n");
      out.write("\t\t\t\t게시물 내용입니다\t게시물 내용입니다\t게시물 내용입니다\t게시물 내용입니다\t게시물 내용입니다\t게시물 내용입니다\t\r\n");
      out.write("\t\t\t\t게시물 내용입니다\t게시물 내용입니다\t게시물 내용입니다\t게시물 내용입니다\t게시물 내용입니다\t게시물 내용입니다\t\r\n");
      out.write("\t\t\t\t게시물 내용입니다\t게시물 내용입니다\t게시물 내용입니다\t게시물 내용입니다\t게시물 내용입니다\t게시물 내용입니다\t\r\n");
      out.write("\t\t\t\t</p>\t\t\t\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t<!-- post Content div end-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- comment Content div start-->\r\n");
      out.write("\t\t<div style='margin-top: 5vh;' align=\"center\">\r\n");
      out.write("\t\t\t<h3>댓글 내용입니다.</h3>\r\n");
      out.write("\t\t\t\t<table style='width: 81.5%;'>\r\n");
      out.write("\t\t\t\t");
for(int i=1;i<=10;i++){
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr style='width: 100%;'>\r\n");
      out.write("\t\t\t\t\t\t<td style='width: 10%; border: 1px solid black;'>\r\n");
      out.write("\t\t\t\t\t\t\t작성자");
      out.print(i );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<td style='width: 70%; border: 1px solid black;'>\r\n");
      out.write("\t\t\t\t\t\t\t작성내용");
      out.print(i );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<td style='width: 20%; border: 1px solid black;'>\r\n");
      out.write("\t\t\t\t\t\t\t작성일자");
      out.print(i );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
if(session.getAttribute("userId")!=null){
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr style='width: 100%;'>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type='text' readonly=\"readonly\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type='text' style='width: 99%;' placeholder=\"댓글 내용입력하세요\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type='button'>댓글 등록</button>\r\n");
      out.write("\t\t\t\t\t\t</td>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</table>\t\t\t\t\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t<!-- comment Content div end-->\t\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- content div ends-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$('#auctonBtn').click(function() {\r\n");
      out.write("\t\t\tif(confirm($('#increasePrice').val()+'원에 입찰하시겠습니까?')){\r\n");
      out.write("\t\t\t\talert($('#increasePrice').val()+'원에 입찰되었습니다!');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t$('#buyNowBtn').click(function() {\r\n");
      out.write("\t\t\tif(confirm('itemMaxPrice원에 즉시구매 하시겠습니까?')){\r\n");
      out.write("\t\t\t\t$('#auctionOrBuyNow').attr('action','/action/s_post_buyNow.action');\r\n");
      out.write("\t\t\t\t$('#auctionOrBuyNow').submit();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t$('#myListBtn').click(function() {\r\n");
      out.write("\t\t\tif(confirm('관심상품 목록에 등록하시겠습니까?')){\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div id='commercial' style='width: 19.5%; height: 80vh; border-color: black; border-style: solid; border-width: 1px; float: left;' align=\"center\">\t\t\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/ad/ad.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\t\t\t\t\r\n");
      out.write("\t<div id='footer' style='width: 99.8%; height: 10vh; border-color: black; border-style: solid; border-width: 1px; float: none;' align=\"center\" >\t\t\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/footer/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\t\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$('#footer').ready(function() {\r\n");
      out.write("\t\t\t$('#footer').css('margin-top',$('#content').css('height'));\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t$('window').resize(function() {\r\n");
      out.write("\t\t\t$('#footer').css('margin-top',$('#content').css('height'));\r\n");
      out.write("\t\t})\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
