/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.15
 * Generated at: 2017-10-10 00:51:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.post.bpost;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.in.team2.vo.PostVO;
import java.util.List;
import java.util.ArrayList;
import java.util.Date;
import com.in.team2.vo.CommentVO;

public final class p_005fbpost_005fdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/user/Desktop/team2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/team2/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1503031307456L));
    _jspx_dependants.put("jar:file:/C:/Users/user/Desktop/team2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/team2/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.in.team2.vo.PostVO");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("com.in.team2.vo.CommentVO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<script src='/jquery/jquery-3.2.1.js'></script>\r\n");
      out.write("<script>\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("        $(\"#modify\").click(function(){\r\n");
      out.write("            document.form1.action=\"/action/B_post_updatePost/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.postNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("            document.form1.submit();\r\n");
      out.write("        });\r\n");
      out.write("        $(\"#delete\").click(function(){\r\n");
      out.write("        \tif(confirm(\"삭제하시겠습니까?\")){\r\n");
      out.write("        \tdocument.form1.action=\"/action/B_post_deletePost\" ;\r\n");
      out.write("            document.form1.submit();\r\n");
      out.write("        \t}\r\n");
      out.write("        });\r\n");
      out.write("       \r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("\t<div id='menuDiv' style='width: 100%; height: 10vh; border-color: black; border-style: solid; border-width: 1px;'>\t\t\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/menubar/menubar.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t<div id='chat' style='width: 20%; height: 80vh; border-color: black; border-style: solid; border-width: 1px; float: left;' align=\"center\">\t\t\t\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/chat/chat.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div id='content' style='width: 60%; border-color: black; border-style: solid; border-width: 1px; float: left; min-height: 80vh;overflow: auto;'>\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form name=\"form1\" method = 'post'>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div style='height:40vh; width: 90%; margin-top: 5vh; margin-left: 5%;'>\r\n");
      out.write("\t\t\t<!-- 제목 div 시작 -->\r\n");
      out.write("\t\t\t<div style='height:5vh; width: 90.2%; border: 1px solid black;'>\r\n");
      out.write("\t\t\t\t<div style=\"float: left;width: 50%;\"><a>제목: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.postTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a></div>\r\n");
      out.write("\t\t\t\t<div style=\"float: left;width: 14%;\" align=\"right\"><a>작성자: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a></div>\t\r\n");
      out.write("\t\t\t\t<div style=\"float: left;width: 35%;\" align=\"right\"><a>등록일: ");
      if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_page_context))
        return;
      out.write("</a></div>\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 제목 div end-->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- photo div start-->\r\n");
      out.write("\t\t\t<div style='height:40vh; width: 60%; border: 1px solid black; float: left'>\r\n");
      out.write("\t\t\t\t<img src = '/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.postPhoto }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' style=\"width: 100%; height: 40vh;\">\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- photo div end-->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- informatoin div start-->\r\n");
      out.write("\t\t\t<input name='postNum' type=\"hidden\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.postNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>\r\n");
      out.write("\t\t\t<div style='height:40vh; width: 30%; border: 1px solid black; float: left;'>\r\n");
      out.write("\t\t\t\t<input type=\"text\" readonly value='상품 카테고리 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.itemCategory}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' style='width:98.81%; height:25%; '><br>\r\n");
      out.write("\t\t\t\t<input type=\"text\" readonly value='상세 상품명 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.itemName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' style='width:98.81%; height: 25%; '><br>\r\n");
      out.write("\t\t\t\t<input type=\"text\" readonly value='상품 등급 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.itemClass}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' style='width:49%; height: 25%;' ><a>등급 기준 보기</a><br>\r\n");
      out.write("\t\t\t\t<input type=\"text\" readonly value='쪽지 보내기' style='width:98.81%; height: 7.6vh; '><br>\t\t\t\t\r\n");
      out.write("\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t<!-- informatoin div ends-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- post Content div start-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div style='width: 81.2%; margin-top: 5.3vh; margin-left: 5%; border: 1px solid black'>\t\t\r\n");
      out.write("\t\t\t\t<div style=\"padding-top: 2vh;\">\r\n");
      out.write("\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.postContent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t");

			PostVO detail = (PostVO)request.getAttribute("detail");
			if(session.getAttribute("userId")!=null&&session.getAttribute("userId").equals(detail.getUserId())){
			 
      out.write("\r\n");
      out.write("\t\t\t<button id = 'modify' type=\"button\" style=\"height: 3vh; float: right;\">게시글 수정</button>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t");
if(session.getAttribute("userId")!=null&&(session.getAttribute("userId").equals(detail.getUserId())||session.getAttribute("userId").equals("ADMIN"))){
      out.write("\r\n");
      out.write("\t\t\t<button id = 'delete' type=\"button\" style=\"height: 3vh; float: right;\">게시글 삭제</button>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t");

			List <CommentVO> commentList =(List)request.getAttribute("comment");
			if(commentList.size()>0){
			
      out.write("\r\n");
      out.write("\t\t<!-- post Content div end-->\r\n");
      out.write("\t\t<div style='margin-top: 5vh;' align=\"center\">\r\n");
      out.write("\t\t\t<h3>댓글</h3>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t<!-- comment Content div start-->\r\n");
      out.write("\t\t");

			for(int t=0;t<commentList.size();t++){
				CommentVO result = commentList.get(t);
				
			
      out.write("\r\n");
      out.write("\t\t<div style='margin-top: 5vh;' align=\"center\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<div style='height:15vh; width: 90%; border: 1px solid black; '>\t\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<input id=\"userId\" name='userId' readonly value=\"");
      out.print(result.getUserId() );
      out.write("\" style='height:5vh; width: 10%;  float: left'>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<input value=\"");
      out.print(result.getRegDate() );
      out.write(" \" readonly=\"readonly\" id=\"regDate\" name='regDate' type=\"text\" style='height:5vh; width: 79.2%;  float: left'>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t");
if(session.getAttribute("userId")!=null&&session.getAttribute("userId").equals(result.getUserId())){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<button id='");
      out.print(result.getCommentNum());
      out.write("' class=\"update\" type=\"button\" style='height:54px; width: 5%; float: left;' >댓글 수정</button>\r\n");
      out.write("\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t");
if(session.getAttribute("userId")!=null&&(session.getAttribute("userId").equals(result.getUserId())||session.getAttribute("userId").equals("ADMIN"))){
      out.write("\r\n");
      out.write("\t\t\t\t\t<button id='");
      out.print(result.getCommentNum());
      out.write("' class = 'deletebtn' type=\"button\" style='height:54px; width: 5%; float: left' >댓글 삭제</button>\r\n");
      out.write("\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t \t<textarea id=\"comment");
      out.print(result.getCommentNum());
      out.write("\" readonly style='height:83px; width: 99.4%; resize: none; float: left'>");
      out.print(result.getCommentContent() );
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t");

		}
		
      out.write(" \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
if(session.getAttribute("userId")!=null){ 
      out.write("\r\n");
      out.write("\t\t<form id=\"form3\" name=\"form3\" method = 'post' >\r\n");
      out.write("\t\t<div style='margin-top: 5vh; margin-bottom: 5vh; '  align=\"center\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<h3>댓글 입력</h3>\r\n");
      out.write("\t\t\t<input id=\"userId\" name='userId' type=\"hidden\" value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("\t\t\t<input id=\"postNum\" name='postNum' type=\"hidden\" value=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.postNum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" >\r\n");
      out.write("\t\t\t<input type='hidden' name='commentNum' id='commentNum' value=0>\r\n");
      out.write("\t\t\t<table style='width: 81.5%;'>\r\n");
      out.write("\t\t\t\t<tr style='width: 100%;'>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<textarea rows=\"5\" cols=\"80\" id=\"commentContent\" name=\"commentContent\" style='width: 99%;\r\n");
      out.write("\t\t\t\t\t\tresize: none; ' placeholder=\"댓글을 작성해주세요\"></textarea>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<button type='button' id = 'createbtn'>댓글 등록</button>\r\n");
      out.write("\t\t\t\t\t</td>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t");
 }
      out.write("\r\n");
      out.write("\t\t<!-- comment Content div end-->\t\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- content div ends-->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(\".deletebtn\").click(function(){\r\n");
      out.write("\t\t\tif(confirm(\"삭제하시겠습니까?\")){\r\n");
      out.write("\t\t\t$('#commentNum').val($(this).attr('id'));\r\n");
      out.write("\t\t\tdocument.form3.action=\"/action/B_post_deleteComment/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.postNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\t\tdocument.form3.submit();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t var flag = false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t $(\".update\").click(function(){\r\n");
      out.write("\t\t\t var id = $(this).attr('id');\r\n");
      out.write("\t\t\tvar comment = $(\"#comment\"+id).val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(flag == false){\r\n");
      out.write("\t\t\t /* $(\"#comment\"+id).attr(\"readonly\", false);  */\r\n");
      out.write("\t\t\t  $(\"#comment\"+id).removeAttr(\"readonly\")  \r\n");
      out.write("\t\t\t flag=true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\telse if(flag == true){\r\n");
      out.write("\t\t\t  if (comment == \"\"){\r\n");
      out.write("\t\t\t\t\talert(\"제목을 입력하세요\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t\t$(\"#commentNum\").val(id);\r\n");
      out.write("\t\t\t\t$(\"#commentContent\").val(comment);\r\n");
      out.write("\t\t\t\t/* \r\n");
      out.write("\t\t\t\t$(\"#form3\").attr('action', '/action/B_post_modifyComment/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.postNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\r\n");
      out.write("\t\t\t\t$(\"#form3\").attr('method', 'post');\r\n");
      out.write("\t\t\t\t$(\"#form3\").submit();   \r\n");
      out.write("\t\t\t\t*/\r\n");
      out.write("\t\t\t\tdocument.form3.action=\"/action/B_post_modifyComment/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.postNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\t\t\tdocument.form3.submit(); \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t$(\"#createbtn\").click(function(){\r\n");
      out.write("\t\t\tvar commentContent = $(\"#commentContent\").val();\r\n");
      out.write("\t        if(commentContent == \"\"){\r\n");
      out.write("\t        \talert(\"제목을 입력하세요\");\r\n");
      out.write("\t            document.form3.commentContent.focus();\r\n");
      out.write("\t            return;\r\n");
      out.write("\t        }\r\n");
      out.write("\t    document.form3.action=\"/action/B_post_createComment/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.postNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t    document.form3.submit();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div id='commercial' style='width: 19.5%; height: 80vh; border-color: black; border-style: solid; border-width: 1px; float: left;' align=\"center\">\t\t\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/ad/ad.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\t\t\t\t\r\n");
      out.write("\t<div id='footer' style='width: 99.8%; height: 10vh; border-color: black; border-style: solid; border-width: 1px; float: none;' align=\"center\" >\t\t\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/footer/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\r\n");
      out.write("\t\t$('#footer').ready(function() {\r\n");
      out.write("\t\t\t$('#footer').css('margin-top',$('#content').css('height'));\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t$('window').resize(function() {\r\n");
      out.write("\t\t\t$('#footer').css('margin-top',$('#content').css('height'));\r\n");
      out.write("\t\t})\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent(null);
      // /WEB-INF/views/post/bpost/p_bpost_detail.jsp(56,63) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.regDate}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/post/bpost/p_bpost_detail.jsp(56,63) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd a HH:mm:ss");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }
}
