/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.15
 * Generated at: 2017-10-10 06:08:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class p_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<script src='/jquery/jquery-3.2.1.js'></script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("\t<div id='menuDiv'>\t\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/menubar/menubar.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t<div id='chat'>\t\t\t\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/chat/chat.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div id='content'>\t\t\t\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<h1>お知らせ！</h1>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t<div style='margin-left: 100px;'>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<ins>販売掲示板</ins>\t\t\t\t\r\n");
      out.write("\t\t\t\t<li>販売掲示板の検索、ペイジング機能はまだ準備中です！申し訳ございません!\r\n");
      out.write("\t\t\t\t\t<img src='/resources/img/banner/banner_main_sorry1.jpg' style=\"width: 600px;height: 300px; display:block;\">\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>販売掲示板にご登録してから１時間後、販売品の入札が終わります。\r\n");
      out.write("\t\t\t\t\t入札が終わると販売の方、購買の方にお知らせのメールをお届けしますが、１０分ほどの差がある可能背があります。\r\n");
      out.write("\t\t\t\t\t<img src='/resources/img/banner/banner_onehour.png' style=\"width: 400px;height: 400px; display: block;\">\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<ins>購買掲示板・Q/A掲示板</ins>\t\t\t\t\r\n");
      out.write("\t\t\t\t<li>デザインがまだです!申し訳ございません（2）!\r\n");
      out.write("\t\t\t\t\t<img src='/resources/img/banner/banner_main_sorry2.jpg' style=\"width: 600px;height: 300px; display:block;\">\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- <h1>수정 및 확인 사항</h1>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<ins>구매 게시판</ins>\t\t\t\t\r\n");
      out.write("\t\t\t\t<li>구매 게시판 쪽 DB 정보 변경 시 USER_ID 확인 조건 추가</li>\r\n");
      out.write("\t\t\t\t<li>왜 새로 만든 VO에 static 변수가 들어가는지?</li>\t\t\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<ul><ins>판매 게시판</ins>\t\t\t\r\n");
      out.write("\t\t\t\t<li>판매 게시판 view 단 spost 폴더 밑으로 넣었으니 주의할 것</li>\r\n");
      out.write("\t\t\t\t<li>판매 게시판 쪽 입찰하기, 입찰 취소,답글 달기는 로그인한 유저에 한해서 할 것</li>\r\n");
      out.write("\t\t\t\t<li>판매 게시판 쪽 특수문자 처리하기</li>\r\n");
      out.write("\t\t\t\t<li>판매 게시판 만료되면 SELL_POST 디테일을 찾는 게 아니라 입찰자 명단 보여줄 것</li>\r\n");
      out.write("\t\t\t\t<li>판매 게시판 입찰 등록, 입찰 취소는 만료 기한이 지나면 하지 못하도록 막아놓을 것</li>\r\n");
      out.write("\t\t\t\t<li>판매 게시판 쪽 에러 발생 시 롤백하기</li>\r\n");
      out.write("\t\t\t\t<li>입찰 만료 시간은 등록시간+1시간, 판매 게시물 삭제 시간은 만료시간+1 시간으로 변경</li>\t\t\t\t\r\n");
      out.write("\t\t\t</ul> -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- content div ends-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div id='commercial' align=\"center\">\t\t\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/ad/ad.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\t\t\t\t\r\n");
      out.write("\t<div id='footer' align=\"center\">\t\t\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/footer/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
