/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.15
 * Generated at: 2017-10-10 06:41:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.post.spost;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.in.team2.vo.AuctionVO;
import com.in.team2.vo.CommentVO;
import java.util.List;
import java.util.ArrayList;
import com.in.team2.vo.PostVO;

public final class p_005fspost_005fdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/user/Desktop/team2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/team2/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1503031307456L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.in.team2.vo.PostVO");
    _jspx_imports_classes.add("com.in.team2.vo.AuctionVO");
    _jspx_imports_classes.add("com.in.team2.vo.CommentVO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<script src='/jquery/jquery-3.2.1.js'></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 관심상품 중복등록시 경고메시지 출력 -->\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("\t<div id='menuDiv'>\t\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/menubar/menubar.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t<div id='chat'>\t\t\t\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/chat/chat.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<!-- PostVO 변수 만들기 -->\t\r\n");
PostVO detail = (PostVO)request.getAttribute("detail");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id='content'>\r\n");
      out.write("\t\t<div style='height:40vh; width: 90%; margin-top: 5vh; margin-left: 5%;'>\r\n");
      out.write("\t\t<!-- 제목 div 시작 -->\r\n");
      out.write("\t\t\t<div style='height:5vh; width: 90.2%; border: 1px solid black;'>\r\n");
      out.write("\t\t\t\t<div style=\"float: left;width: 70%;\"><a>タイトル:");
      out.print(detail.getPostTitle() );
      out.write("</a></div>\r\n");
      out.write("\t\t\t\t<div style=\"float: left;width: 29%;\" align=\"right\"><a>作成者: ");
      out.print(detail.getUserId());
      out.write("\t登録日:");
      out.print(detail.getRegDate() );
      out.write("</a></div>\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<!-- 제목 div end-->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<!-- photo div start-->\r\n");
      out.write("\t\t\t<div style='height:40vh; width: 60%; border: 1px solid black; float: left; min-height: 288px;'>\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print("/"+detail.getPostPhoto() );
      out.write("\" style='width: 100%;height: 40vh; min-height: 288px;'>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<!-- photo div end-->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<!-- informatoin div start-->\r\n");
      out.write("\t\t\t<form id='auctionOrBuyNow' method='post'>\r\n");
      out.write("\t\t\t\t<input name='postNum' type=\"hidden\" id='postNum' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.postNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div style='display:table; height:40vh; width: 30%; border: 1px solid black; float: left; min-height: 288px;'>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<div style='display: table-row; width: 100%;'>\r\n");
      out.write("\t\t\t\t\t\t<div style='display: table-cell; width: 30%;'>\r\n");
      out.write("\t\t\t\t\t\t\t製造社: \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style='display: table-cell; width: 68%;'>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" readonly value='");
      out.print(detail.getItemCategory());
      out.write("' style='width:98.5%; height: 4vh; '>\r\n");
      out.write("\t\t\t\t\t\t</div>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div style='display: table-row; width: 100%;'>\r\n");
      out.write("\t\t\t\t\t\t<div style='display: table-cell; width: 30%;'>\r\n");
      out.write("\t\t\t\t\t\t\t商品名: \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style='display: table-cell; width: 68%;'>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" readonly value='");
      out.print(detail.getItemName() );
      out.write("' style='width:99%; height: 4vh;'>\r\n");
      out.write("\t\t\t\t\t\t</div>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div style='display: table-row; width: 100%;'>\r\n");
      out.write("\t\t\t\t\t\t<div style='display: table-cell; width: 30%;'>\r\n");
      out.write("\t\t\t\t\t\t\t商品等級: \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style='display: table-cell; width: 68%;'>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" readonly value='");
      out.print(detail.getItemClass() );
      out.write("' style='width:99%; height: 3vh;'>\r\n");
      out.write("\t\t\t\t\t\t</div>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div style='display: table-row; width: 100%;'>\r\n");
      out.write("\t\t\t\t\t\t<div style='display: table-cell; width: 30%;'>\r\n");
      out.write("\t\t\t\t\t\t\t現在価格: \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style='display: table-cell; width: 68%;'>\r\n");
      out.write("\t\t\t\t\t\t\t<input id='itemCurPrice' name='itemCurPrice' type=\"text\" readonly value='");
      out.print(detail.getItemCurPrice());
      out.write("' style='height: 3vh; width: 99%'>\r\n");
      out.write("\t\t\t\t\t\t</div>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div style='display: table-row; width: 100%;'>\r\n");
      out.write("\t\t\t\t\t\t<div style='display: table-cell; width: 40%;'>\r\n");
      out.write("\t\t\t\t\t\t\t入札満了日: \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style='display: table-cell; width: 58%;'>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name = 'itemExpireDate' readonly value='");
      out.print(detail.getItemExpireDate() );
      out.write("' style='height: 3vh; width: 99%'>\r\n");
      out.write("\t\t\t\t\t\t</div>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div style='display: table-row; width: 100%;'>\r\n");
      out.write("\t\t\t\t\t\t<div style='display: table-cell; width: 30%;'>\r\n");
      out.write("\t\t\t\t\t\t\t引き上げ幅: \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style='display: table-cell; width: 68%;'>\r\n");
      out.write("\t\t\t\t\t\t\t<input id = 'itemIncrease' name='itemIncrease' type=\"text\" readonly value='");
      out.print(detail.getItemIncrease());
      out.write("' style='height: 3vh; width: 99%'>\r\n");
      out.write("\t\t\t\t\t\t</div>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<input name='sellerId' type='hidden' value='");
      out.print(detail.getUserId());
      out.write("'>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div style=\"display: table; padding-top: 20px; width: 100%\">\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<button id= 'showSAuctionList' type=\"button\" style='width:45%;  float: left;'>入札者リスト</button>\r\n");
      out.write("\t\t\t\t\t\t");
if(session.getAttribute("userId")!=null&&session.getAttribute("userId").equals(detail.getUserId())){ 
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
} else if(session.getAttribute("userId")!=null&&!session.getAttribute("userId").equals("")){
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t<button id= 'auctionBtn' type=\"button\" style='width:45%;  float: left;'>入札する</button>\r\n");
      out.write("\t\t\t\t\t\t<button id= 'auctionCancelBtn' type=\"button\" style='width:45%; float: left;'>入札取り消し</button>\r\n");
      out.write("\t\t\t\t\t\t<button id= 'myListBtn' type=\"button\" style='width:45%;  float: left;'>マイリスト登録</button>\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t<!-- informatoin div ends-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- post Content div start-->\r\n");
      out.write("\t\t<div style='width: 81.5%;  margin-top: 5vh; margin-left: 5%;'>\t\t\r\n");
      out.write("\t\t\t<div class='postContentDiv' style=\"padding-top: 5vh;\">\t\t\r\n");
      out.write("\t\t\t\t<textarea class='postContentTextArea' readonly style=\"width: 99.3%; resize: none; display: none\" >");
      out.print(detail.getPostContent());
      out.write("</textarea>\t\t\t\r\n");
      out.write("\t\t\t</div>\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("\t\t\t\t$('.postContentTextArea').ready(function(){\r\n");
      out.write("\t\t\t\t\tvar contentText = $('.postContentTextArea').text();\t\t\t\r\n");
      out.write("\t\t\t\t\t$('.postContentDiv').append(contentText.replace(/\\r?\\n/g,\"<br>\"));\r\n");
      out.write("\t\t\t\t\trelocateFooter();\r\n");
      out.write("\t\t\t\t})\t\t\t\t\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div style='width: 100%; padding-top: 5vh;' align=\"center\">\t\t\t\r\n");
      out.write("\t\t\t<button type='button' style='margin-left: 0%;margin-top: 0.5vh' onclick=\"document.location.href='/action/S_post_showList'\">戻る</button>\r\n");
      out.write("\t\t\t");
if(session.getAttribute("userId")!=null&&(session.getAttribute("userId").equals(detail.getUserId())||session.getAttribute("userId").equals("ADMIN"))){ 
      out.write("\t\r\n");
      out.write("\t\t\t\t<button type='button' class='postDelete' id='");
      out.print(detail.getPostNum());
      out.write("' style='margin-left: 0%;margin-top: 0.5vh'>削除</button>\t\r\n");
      out.write("\t\t\t\t<button type='button'  class='postModify' id='");
      out.print(detail.getPostNum());
      out.write("' style='margin-top: 0.5vh'>修正</button>\t\r\n");
      out.write("\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t<!-- post Content div end-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- comment Content div start-->\r\n");
      out.write("\t\t<div style='margin-top: 5vh;' align=\"center\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!--댓글추가 폼 시작  -->\r\n");
      out.write("\t\t\t<form class='commentList' style='margin-left:-5.8%'>\r\n");
      out.write("\t\t\t\t<input name='postNum' type=\"hidden\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.postNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>\r\n");
      out.write("\t\t\t \t<input name='commentNum' type=\"hidden\" id='commentNum' value='0'>\r\n");
      out.write("\t\t\t \t\r\n");
      out.write("\t\t\t \t\r\n");
      out.write("\t\t\t\t<table style='width: 80.5%;'>\t\r\n");
      out.write("\t\t\t");
for(int i=0;i<detail.getCommentList().size();i++){
				 CommentVO comment = detail.getCommentList().get(i);
      out.write("\r\n");
      out.write("\t<tr style='width: 100%;'>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<td style='width: 10%; border: 1px solid black;'>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(comment.getUserId() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<td style='width: 70%; border: 1px solid black;'>\r\n");
      out.write("\t\t\t\t\t\t\t<!--댓글 내용  -->\r\n");
      out.write("\t\t\t\t\t\t\t<textarea readonly id=\"commentContent");
      out.print(comment.getCommentNum());
      out.write("\" style='margin: 0px; width: 97%; height: 7vh; resize:none;'>");
      out.print(comment.getCommentContent() );
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<td style='width: 10%; border: 1px solid black;'>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 댓글 작성일 -->\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(comment.getRegDate() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\" style='width: 10%;'>\r\n");
      out.write("\t\t\t\t\t\t\t");
if(session.getAttribute("userId")!=null&&session.getAttribute("userId").equals(comment.getUserId())){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type='button'  class='commentModify' id='");
      out.print(comment.getCommentNum());
      out.write("' style='margin-bottom: 10%'>修正</button>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type='button'  class='commentDelete' id='");
      out.print(comment.getCommentNum());
      out.write("' style='margin-bottom: 10%'>削除</button>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t");
} else if(session.getAttribute("userId").equals("ADMIN")){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<button type='button'  class='commentDelete' id='");
      out.print(comment.getCommentNum());
      out.write("' style='margin-bottom: 10%'>削除</button>\t\r\n");
      out.write("\t\t\t\t\t\t\t</td>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</tr>\t\t\t\r\n");
      out.write("\t\t");
} 
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t<input name=\"userId\" type='text' readonly=\"readonly\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t</td>\t\r\n");
      out.write("\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t<input id='commentContent' name=\"commentContent\" type='text' style='width: 99%;' placeholder=\"コメントを入力\" >\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t<button type='submit' formaction=\"/action/S_post_createComment\" formmethod=\"post\" >登録</button>\t\t\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\t\r\n");
      out.write("\t\t\t\t</table>\t\t\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t<!-- comment Content div end-->\t\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- content div ends-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\r\n");
      out.write("\t/* 게시물 삭제 */\r\n");
      out.write("\t$('.postDelete').click(function(){\r\n");
      out.write("\t\t$('#postNum').val($(this).attr('id'));\r\n");
      out.write("\t\t\t$('#auctionOrBuyNow').attr('action','/action/S_post_deletePost')\r\n");
      out.write("\t\t\t$('#auctionOrBuyNow').attr('method','post');\r\n");
      out.write("\t\t\t$('#auctionOrBuyNow').submit();\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/* 입찰하기 */\r\n");
      out.write("\t\t$('#auctionBtn').click(function() { \r\n");
      out.write("\t\t\tvar itemCurPrice = Number($('#itemCurPrice').val());\r\n");
      out.write("\t\t\tvar increasePrice = Number($('#itemIncrease').val());\r\n");
      out.write("\t\t\tvar resultPrice = Number(itemCurPrice+increasePrice); \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(confirm(resultPrice+'원에 입찰하시겠습니까?')){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t/* 입찰하러 넘어가는 길 */\r\n");
      out.write("\t\t\t\t$('#auctionOrBuyNow').attr('action','/action/S_post_auction')\r\n");
      out.write("\t\t\t \t$('#auctionOrBuyNow').attr('method','post');\r\n");
      out.write("\t\t\t \t$('#auctionOrBuyNow').submit();\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\talert(resultPrice+'원에 입찰되었습니다!');\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\talert('입찰이 취소되었습니다.');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t/* 댓글 삭제 */\r\n");
      out.write("\t\t\t$('.commentDelete').click(function(){\r\n");
      out.write("\t\t\t\t$('#commentNum').val($(this).attr('id'));\r\n");
      out.write("\t\t\t\t$('.commentList').attr('action','/action/S_post_deleteComment')\r\n");
      out.write("\t \t\t\t$('.commentList').attr('method','post');\r\n");
      out.write("\t \t\t\t$('.commentList').submit();\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar flag = false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t/* 댓글 수정; 한번 누르면 readonly 해제, 두번 누를때 DB수정*/\r\n");
      out.write("\t\t\t$('.commentModify').click(function(){\r\n");
      out.write("\t\t\t\tvar id=$(this).attr('id');\t\t\t\t\r\n");
      out.write("\t\t\t\tif(flag == false){\r\n");
      out.write("\t\t\t\tflag = true;\r\n");
      out.write("\t\t\t\t\t$('#commentContent'+id).attr('readonly',false);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tflag = false;\r\n");
      out.write("\t\t\t\t\t$('#commentContent'+id).attr('readonly',true);\r\n");
      out.write("\t\t\t\t\t$('#commentNum').val(id);\r\n");
      out.write("\t\t\t\t\t$('#commentContent').val($('#commentContent'+id).val());\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$('.commentList').attr('action','/action/S_post_modifyComment')\r\n");
      out.write("\t\t \t\t\t$('.commentList').attr('method','post');\r\n");
      out.write("\t\t \t\t\t$('.commentList').submit(); \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\r\n");
      out.write("\t/* 본문수정폼으로 가기 */\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('.postModify').click(function(){\r\n");
      out.write("\t\t\t$('#postNum').val($(this).attr('id'));\r\n");
      out.write("\t\t\t$('#auctionOrBuyNow').attr('action','/action/l_spost_UpdateView')\r\n");
      out.write(" \t\t\t$('#auctionOrBuyNow').attr('method','post');\r\n");
      out.write(" \t\t\t $('#auctionOrBuyNow').submit();\r\n");
      out.write("\t\t})\r\n");
      out.write("\t/* 입찰 취소*/\r\n");
      out.write("\t\t \t$('#auctionCancelBtn').click(function(){\r\n");
      out.write("\t\t\t$('#auctionOrBuyNow').attr('action','/action/S_post_auctionCancel')\r\n");
      out.write(" \t\t\t$('#auctionOrBuyNow').attr('method','post');\r\n");
      out.write(" \t\t\t\r\n");
      out.write("\t\t\talert('입찰을 취소하셨습니다.');\r\n");
      out.write("\t\t\t$('#auctionOrBuyNow').submit();\r\n");
      out.write("\t\t}) \r\n");
      out.write("\t\t\r\n");
      out.write("\t/* 관심상품 등록 */\r\n");
      out.write("\t\t \t$('#myListBtn').click(function(){\r\n");
      out.write("\t\t\t$('#auctionOrBuyNow').attr('action','/action/User_addMyList')\r\n");
      out.write(" \t\t\t$('#auctionOrBuyNow').attr('method','post');\r\n");
      out.write(" \t\t\t\r\n");
      out.write("\t\t\talert('관심상품에 등록되었습니다.');\r\n");
      out.write("\t\t\t$('#auctionOrBuyNow').submit();\r\n");
      out.write("\t\t}) \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 입찰자현황보기 */\r\n");
      out.write("\t\t  \t$('#showSAuctionList').click(function(){\r\n");
      out.write("\t\t \t\t\t\r\n");
      out.write("\t\t \t\t\twindow.open(\"/jsp/post/s_post/p_spost_auctionList.jsp?postNum=\"+$('#postNum').val(),'name','width=300,height=500');\r\n");
      out.write("\r\n");
      out.write("\t\t})  \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div id='commercial' align=\"center\">\t\t\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/ad/ad.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\t\t\t\t\r\n");
      out.write("\t<div id='footer' align=\"center\">\t\t\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/footer/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\t\t\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/post/spost/p_spost_detail.jsp(19,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty myListError}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<script>\r\n");
          out.write("\talert('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myListError}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("');\r\n");
          out.write("</script>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
